// This file was generated by Prisma, and assumes you have installed:
// pnpm add -D prisma dotenv tsx

import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',

  migrations: {
    path: 'prisma/migrations',

    /*
     * Command executed when running:
     *
     * pnpm exec prisma db seed
     */
    seed: 'tsx prisma/seed.ts',
  },

  datasource: {
    url: process.env['DATABASE_URL'],
  },
});